
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "email": "basic@test.com",
    "firstName": "basic",
    "lastName": "dude",
    "password": "basicM"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "email": "testUser@testing.com",
    "firstName": "test",
    "lastName": "mate",
    "password": "testinG"
}